# Generated by Django 5.0.3 on 2024-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0002_warehouse_warehousetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='icgsaletransactions',
            name='icgtransactionscode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reconcilesaletransactions',
            name='reconciletransactionscode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
