# Generated by Django 5.0.3 on 2024-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0003_icgsaletransactions_icgtransactionscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icgsaletransactions',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reconcilesaletransactions',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
