# Generated by Django 5.0.3 on 2024-03-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0004_icgsaletransactions_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icgsaletransactions',
            name='warehousecode',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='verification_backendapp.warehouse'),
        ),
        migrations.AlterField(
            model_name='reconcilesaletransactions',
            name='warehousecode',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='verification_backendapp.warehouse'),
        ),
    ]
