# Generated by Django 5.0.3 on 2024-03-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0006_alter_icgsaletransactions_warehousecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icgsaletransactions',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reconcilesaletransactions',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
