# Generated by Django 5.0.3 on 2024-03-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0009_alter_icgsaletransactions_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icgsaletransactions',
            name='icgtransactionscode',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reconcilesaletransactions',
            name='reconciletransactionscode',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
