# Generated by Django 5.0.3 on 2024-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_backendapp', '0010_alter_icgsaletransactions_icgtransactionscode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconcilesaletransactions',
            old_name='amount',
            new_name='bank_amount',
        ),
        migrations.RemoveField(
            model_name='reconcilesaletransactions',
            name='warehousecode',
        ),
        migrations.AddField(
            model_name='reconcilesaletransactions',
            name='is_reconcile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconcilesaletransactions',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
